// Code generated by goyacc -o y.go yara.y. DO NOT EDIT.

//line yara.y:2
package parser

import __yyfmt__ "fmt"

//line yara.y:2

import (
	"github.com/sansecio/yargo/ast"
)

//line yara.y:9
type yySymType struct {
	yys        int
	str        string
	num        int64
	byt        byte
	rule       *ast.Rule
	rules      []*ast.Rule
	meta       []*ast.MetaEntry
	metaEntry  *ast.MetaEntry
	stringDef  *ast.StringDef
	stringDefs []*ast.StringDef
	strVal     ast.StringValue
	mods       ast.StringModifiers
	hexTokens  []ast.HexToken
	hexToken   ast.HexToken
	expr       ast.Expr
	exprs      []ast.Expr
}

const (
	RULE           = 57346
	META           = 57347
	STRINGS        = 57348
	CONDITION      = 57349
	IDENT          = 57350
	STRING_LIT     = 57351
	STRING_IDENT   = 57352
	REGEX_LIT      = 57353
	MODIFIER       = 57354
	COND_IDENT     = 57355
	COND_STRING_ID = 57356
	STRING_PATTERN = 57357
	HEX_JUMP       = 57358
	HEX_ALT        = 57359
	INT_LIT        = 57360
	HEX_BYTE       = 57361
	HEX_WILDCARD   = 57362
	AND            = 57363
	OR             = 57364
	NOT            = 57365
	AT             = 57366
	ANY            = 57367
	ALL            = 57368
	OF             = 57369
	THEM           = 57370
	EQ             = 57371
	NE             = 57372
	LT             = 57373
	GT             = 57374
	LE             = 57375
	GE             = 57376
	FILESIZE       = 57377
)

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"RULE",
	"META",
	"STRINGS",
	"CONDITION",
	"IDENT",
	"STRING_LIT",
	"STRING_IDENT",
	"REGEX_LIT",
	"MODIFIER",
	"COND_IDENT",
	"COND_STRING_ID",
	"STRING_PATTERN",
	"HEX_JUMP",
	"HEX_ALT",
	"INT_LIT",
	"HEX_BYTE",
	"HEX_WILDCARD",
	"AND",
	"OR",
	"NOT",
	"AT",
	"ANY",
	"ALL",
	"OF",
	"THEM",
	"EQ",
	"NE",
	"LT",
	"GT",
	"LE",
	"GE",
	"FILESIZE",
	"'{'",
	"'}'",
	"':'",
	"'='",
	"'('",
	"')'",
	"','",
}

var yyStatenames = [...]string{}

const (
	yyEofCode          = 1
	yyErrCode          = 2
	yyInitialStackSize = 16
)

//line yara.y:358

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 63,
	29, 0,
	30, 0,
	31, 0,
	32, 0,
	33, 0,
	34, 0,
	-2, 33,
	-1, 64,
	29, 0,
	30, 0,
	31, 0,
	32, 0,
	33, 0,
	34, 0,
	-2, 34,
	-1, 65,
	29, 0,
	30, 0,
	31, 0,
	32, 0,
	33, 0,
	34, 0,
	-2, 35,
	-1, 66,
	29, 0,
	30, 0,
	31, 0,
	32, 0,
	33, 0,
	34, 0,
	-2, 36,
	-1, 67,
	29, 0,
	30, 0,
	31, 0,
	32, 0,
	33, 0,
	34, 0,
	-2, 37,
	-1, 68,
	29, 0,
	30, 0,
	31, 0,
	32, 0,
	33, 0,
	34, 0,
	-2, 38,
}

const yyPrivate = 57344

const yyLast = 125

var yyAct = [...]int8{
	28, 27, 43, 42, 83, 84, 93, 92, 72, 55,
	44, 45, 46, 47, 48, 49, 34, 33, 70, 37,
	73, 35, 69, 56, 41, 19, 29, 18, 31, 32,
	71, 50, 51, 90, 91, 17, 88, 89, 36, 22,
	53, 21, 16, 30, 61, 62, 63, 64, 65, 66,
	67, 68, 34, 33, 86, 74, 76, 35, 43, 42,
	6, 52, 54, 77, 31, 32, 44, 45, 46, 47,
	48, 49, 78, 58, 36, 59, 25, 82, 43, 30,
	81, 85, 26, 39, 5, 94, 44, 45, 46, 47,
	48, 49, 44, 45, 46, 47, 48, 49, 9, 12,
	60, 40, 10, 11, 12, 8, 14, 15, 11, 12,
	4, 1, 20, 13, 75, 87, 80, 79, 57, 24,
	38, 23, 7, 3, 2,
}

var yyPact = [...]int16{
	-1000, -1000, 106, -1000, 76, 24, 97, 102, 92, 5,
	-3, -11, -13, 92, 4, 2, -1000, -1000, 72, 3,
	-18, -1000, -1000, 75, 72, -1000, -15, 37, -1000, 3,
	3, 34, 13, 38, -31, -1000, -1000, -1000, -1000, -16,
	-1000, 64, 3, 3, 3, 3, 3, 3, 3, 3,
	63, -19, -10, -20, 39, 39, 54, -1000, -1000, -1000,
	-1000, 57, 63, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 65, -1000, 62, -1000, -37, -1000, -1000, -1000, 69,
	17, -34, -35, -1000, 39, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 124, 123, 122, 121, 120, 105, 119, 76, 118,
	117, 116, 115, 1, 0, 98, 114, 111,
}

var yyR1 = [...]int8{
	0, 17, 1, 1, 2, 2, 2, 2, 3, 4,
	4, 5, 5, 6, 7, 7, 8, 9, 9, 9,
	10, 10, 11, 11, 12, 12, 12, 12, 15, 13,
	13, 13, 13, 13, 13, 13, 13, 13, 13, 14,
	14, 14, 14, 14, 14, 14, 14, 14, 14, 16,
	16, 16,
}

var yyR2 = [...]int8{
	0, 1, 0, 2, 7, 6, 6, 5, 3, 0,
	2, 3, 3, 3, 1, 2, 4, 1, 1, 3,
	0, 2, 0, 2, 1, 1, 1, 1, 3, 1,
	3, 3, 2, 3, 3, 3, 3, 3, 3, 3,
	3, 5, 3, 5, 3, 4, 1, 1, 1, 0,
	1, 3,
}

var yyChk = [...]int16{
	-1000, -17, -1, -2, 4, 8, 36, -3, -6, -15,
	5, 6, 7, -6, -15, -15, 37, 38, 38, 38,
	-15, 37, 37, -4, -7, -8, 10, -13, -14, 23,
	40, 25, 26, 14, 13, 18, 35, 37, -5, 8,
	-8, 39, 22, 21, 29, 30, 31, 32, 33, 34,
	-13, -13, 27, 27, 24, 40, 39, -9, 9, 11,
	36, -13, -13, -13, -13, -13, -13, -13, -13, 41,
	28, 40, 28, 40, -14, -16, -14, 9, 18, -10,
	-11, 15, 15, 41, 42, 12, 37, -12, 19, 20,
	16, 17, 41, 41, -14,
}

var yyDef = [...]int8{
	2, -2, 1, 3, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 7, 9, 0, 0,
	0, 6, 5, 8, 13, 14, 0, 28, 29, 0,
	0, 0, 0, 46, 0, 47, 48, 4, 10, 0,
	15, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	32, 0, 0, 0, 0, 49, 0, 20, 17, 18,
	22, 30, 31, -2, -2, -2, -2, -2, -2, 39,
	40, 0, 42, 0, 44, 0, 50, 11, 12, 16,
	0, 0, 0, 45, 0, 21, 19, 23, 24, 25,
	26, 27, 41, 43, 51,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	40, 41, 3, 3, 42, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 38, 3,
	3, 39, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 36, 3, 37,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:59
		{
			yylex.(*yaraLexer).ruleSet = &ast.RuleSet{Rules: yyDollar[1].rules}
		}
	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yara.y:66
		{
			yyVAL.rules = nil
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yara.y:70
		{
			yyVAL.rules = append(yyDollar[1].rules, yyDollar[2].rule)
		}
	case 4:
		yyDollar = yyS[yypt-7 : yypt+1]
//line yara.y:77
		{
			yyVAL.rule = &ast.Rule{
				Name:      yyDollar[2].str,
				Meta:      yyDollar[4].meta,
				Strings:   yyDollar[5].stringDefs,
				Condition: yyDollar[6].expr,
			}
		}
	case 5:
		yyDollar = yyS[yypt-6 : yypt+1]
//line yara.y:86
		{
			yyVAL.rule = &ast.Rule{
				Name:      yyDollar[2].str,
				Strings:   yyDollar[4].stringDefs,
				Condition: yyDollar[5].expr,
			}
		}
	case 6:
		yyDollar = yyS[yypt-6 : yypt+1]
//line yara.y:94
		{
			yyVAL.rule = &ast.Rule{
				Name:      yyDollar[2].str,
				Meta:      yyDollar[4].meta,
				Condition: yyDollar[5].expr,
			}
		}
	case 7:
		yyDollar = yyS[yypt-5 : yypt+1]
//line yara.y:102
		{
			yyVAL.rule = &ast.Rule{
				Name:      yyDollar[2].str,
				Condition: yyDollar[4].expr,
			}
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:112
		{
			yyVAL.meta = yyDollar[3].meta
		}
	case 9:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yara.y:119
		{
			yyVAL.meta = nil
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yara.y:123
		{
			yyVAL.meta = append(yyDollar[1].meta, yyDollar[2].metaEntry)
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:130
		{
			yyVAL.metaEntry = &ast.MetaEntry{Key: yyDollar[1].str, Value: unquoteString(yyDollar[3].str)}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:134
		{
			yyVAL.metaEntry = &ast.MetaEntry{Key: yyDollar[1].str, Value: yyDollar[3].num}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:141
		{
			yyVAL.stringDefs = yyDollar[3].stringDefs
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:148
		{
			yyVAL.stringDefs = []*ast.StringDef{yyDollar[1].stringDef}
		}
	case 15:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yara.y:152
		{
			yyVAL.stringDefs = append(yyDollar[1].stringDefs, yyDollar[2].stringDef)
		}
	case 16:
		yyDollar = yyS[yypt-4 : yypt+1]
//line yara.y:159
		{
			yyVAL.stringDef = &ast.StringDef{
				Name:      yyDollar[1].str,
				Value:     yyDollar[3].strVal,
				Modifiers: yyDollar[4].mods,
			}
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:170
		{
			yyVAL.strVal = ast.TextString{Value: unquoteString(yyDollar[1].str)}
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:174
		{
			pattern, mods := parseRegex(yyDollar[1].str)
			yyVAL.strVal = ast.RegexString{Pattern: pattern, Modifiers: mods}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:179
		{
			yyVAL.strVal = ast.HexString{Tokens: yyDollar[2].hexTokens}
		}
	case 20:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yara.y:186
		{
			yyVAL.mods = ast.StringModifiers{}
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yara.y:190
		{
			yyVAL.mods = yyDollar[1].mods
			switch yyDollar[2].str {
			case "ascii":
				yyVAL.mods.Ascii = true
			case "base64":
				yyVAL.mods.Base64 = true
			case "fullword":
				yyVAL.mods.Fullword = true
			case "nocase":
				yyVAL.mods.Nocase = true
			case "private":
				yyVAL.mods.Private = true
			default:
				// known-but-unimplemented (wide, xor, ...), argument forms of
				// supported modifiers, or future modifiers; recorded so the
				// rule is skipped at compile time and reported as a warning
				yyVAL.mods.Unsupported = append(yyVAL.mods.Unsupported, yyDollar[2].str)
			}
		}
	case 22:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yara.y:214
		{
			yyVAL.hexTokens = nil
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yara.y:218
		{
			yyVAL.hexTokens = append(yyDollar[1].hexTokens, yyDollar[2].hexToken)
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:225
		{
			yyVAL.hexToken = ast.HexByte{Value: yyDollar[1].byt}
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:229
		{
			yyVAL.hexToken = ast.HexWildcard{}
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:233
		{
			jump, err := parseHexJump(yyDollar[1].str)
			if err != nil {
				yylex.Error(err.Error())
			}
			yyVAL.hexToken = jump
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:241
		{
			alt, err := parseHexAlt(yyDollar[1].str)
			if err != nil {
				yylex.Error(err.Error())
			}
			yyVAL.hexToken = alt
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:252
		{
			yyVAL.expr = yyDollar[3].expr
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:259
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:263
		{
			yyVAL.expr = ast.BinaryExpr{Op: "or", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:267
		{
			yyVAL.expr = ast.BinaryExpr{Op: "and", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yara.y:271
		{
			yyVAL.expr = ast.NotExpr{Inner: yyDollar[2].expr}
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:275
		{
			yyVAL.expr = comparisonExpr(yylex, "==", yyDollar[1].expr, yyDollar[3].expr)
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:279
		{
			yyVAL.expr = comparisonExpr(yylex, "!=", yyDollar[1].expr, yyDollar[3].expr)
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:283
		{
			yyVAL.expr = comparisonExpr(yylex, "<", yyDollar[1].expr, yyDollar[3].expr)
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:287
		{
			yyVAL.expr = comparisonExpr(yylex, ">", yyDollar[1].expr, yyDollar[3].expr)
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:291
		{
			yyVAL.expr = comparisonExpr(yylex, "<=", yyDollar[1].expr, yyDollar[3].expr)
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:295
		{
			yyVAL.expr = comparisonExpr(yylex, ">=", yyDollar[1].expr, yyDollar[3].expr)
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:302
		{
			yyVAL.expr = ast.ParenExpr{Inner: yyDollar[2].expr}
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:306
		{
			yyVAL.expr = ast.AnyOf{Pattern: "them"}
		}
	case 41:
		yyDollar = yyS[yypt-5 : yypt+1]
//line yara.y:310
		{
			yyVAL.expr = ast.AnyOf{Pattern: yyDollar[4].str}
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:314
		{
			yyVAL.expr = ast.AllOf{Pattern: "them"}
		}
	case 43:
		yyDollar = yyS[yypt-5 : yypt+1]
//line yara.y:318
		{
			yyVAL.expr = ast.AllOf{Pattern: yyDollar[4].str}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:322
		{
			yyVAL.expr = ast.AtExpr{Ref: ast.StringRef{Name: yyDollar[1].str}, Pos: yyDollar[3].expr}
		}
	case 45:
		yyDollar = yyS[yypt-4 : yypt+1]
//line yara.y:326
		{
			yyVAL.expr = ast.FuncCall{Name: yyDollar[1].str, Args: yyDollar[3].exprs}
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:330
		{
			yyVAL.expr = ast.StringRef{Name: yyDollar[1].str}
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:334
		{
			yyVAL.expr = ast.IntLit{Value: yyDollar[1].num}
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:338
		{
			yyVAL.expr = ast.Filesize{}
		}
	case 49:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yara.y:345
		{
			yyVAL.exprs = nil
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:349
		{
			yyVAL.exprs = []ast.Expr{yyDollar[1].expr}
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:353
		{
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].expr)
		}
	}
	goto yystack /* stack new state and value */
}
