// Code generated by goyacc -o y.go yara.y. DO NOT EDIT.

//line yara.y:2
package parser

import __yyfmt__ "fmt"

//line yara.y:2

import (
	"github.com/sansecio/yargo/ast"
)

//line yara.y:9
type yySymType struct {
	yys        int
	str        string
	num        int64
	byt        byte
	rule       *ast.Rule
	rules      []*ast.Rule
	meta       []*ast.MetaEntry
	metaEntry  *ast.MetaEntry
	stringDef  *ast.StringDef
	stringDefs []*ast.StringDef
	strVal     ast.StringValue
	mods       ast.StringModifiers
	hexTokens  []ast.HexToken
	hexToken   ast.HexToken
	expr       ast.Expr
	exprs      []ast.Expr
}

const RULE = 57346
const META = 57347
const STRINGS = 57348
const CONDITION = 57349
const IDENT = 57350
const STRING_LIT = 57351
const STRING_IDENT = 57352
const REGEX_LIT = 57353
const MODIFIER = 57354
const COND_IDENT = 57355
const COND_STRING_ID = 57356
const STRING_PATTERN = 57357
const HEX_JUMP = 57358
const HEX_ALT = 57359
const INT_LIT = 57360
const HEX_BYTE = 57361
const HEX_WILDCARD = 57362
const AND = 57363
const OR = 57364
const AT = 57365
const ANY = 57366
const ALL = 57367
const OF = 57368
const THEM = 57369
const EQ = 57370

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"RULE",
	"META",
	"STRINGS",
	"CONDITION",
	"IDENT",
	"STRING_LIT",
	"STRING_IDENT",
	"REGEX_LIT",
	"MODIFIER",
	"COND_IDENT",
	"COND_STRING_ID",
	"STRING_PATTERN",
	"HEX_JUMP",
	"HEX_ALT",
	"INT_LIT",
	"HEX_BYTE",
	"HEX_WILDCARD",
	"AND",
	"OR",
	"AT",
	"ANY",
	"ALL",
	"OF",
	"THEM",
	"EQ",
	"'{'",
	"'}'",
	"':'",
	"'='",
	"'('",
	"')'",
	"','",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yara.y:322

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 90

var yyAct = [...]int8{
	28, 27, 33, 32, 41, 40, 80, 34, 70, 71,
	79, 42, 47, 30, 31, 77, 78, 56, 75, 76,
	59, 57, 29, 48, 39, 35, 60, 58, 19, 73,
	50, 43, 51, 18, 17, 22, 21, 16, 41, 40,
	6, 42, 53, 54, 55, 42, 41, 61, 63, 45,
	52, 25, 44, 42, 46, 64, 69, 9, 68, 72,
	26, 10, 11, 12, 65, 14, 15, 37, 11, 12,
	8, 20, 81, 5, 12, 4, 38, 1, 13, 62,
	74, 67, 66, 49, 24, 36, 23, 7, 3, 2,
}

var yyPact = [...]int16{
	-1000, -1000, 71, -1000, 65, 11, 56, 62, 67, 7,
	3, 2, -3, 67, 6, 5, -1000, -1000, 50, -11,
	-5, -1000, -1000, 59, 50, -1000, -8, 17, -1000, -11,
	26, 23, 31, -21, -1000, -1000, -1000, -9, -1000, 21,
	-11, -11, -11, -17, -6, -7, -11, -11, 46, -1000,
	-1000, -1000, -1000, 25, 13, -1000, -1000, -1000, 43, -1000,
	41, -1000, -26, -1000, -1000, -1000, 47, -1, -24, -28,
	-1000, -11, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000,
}

var yyPgo = [...]int8{
	0, 89, 88, 87, 86, 85, 70, 84, 51, 83,
	82, 81, 80, 1, 0, 57, 79, 77,
}

var yyR1 = [...]int8{
	0, 17, 1, 1, 2, 2, 2, 2, 3, 4,
	4, 5, 5, 6, 7, 7, 8, 9, 9, 9,
	10, 10, 11, 11, 12, 12, 12, 12, 15, 13,
	13, 13, 13, 14, 14, 14, 14, 14, 14, 14,
	14, 14, 16, 16, 16,
}

var yyR2 = [...]int8{
	0, 1, 0, 2, 7, 6, 6, 5, 3, 0,
	2, 3, 3, 3, 1, 2, 4, 1, 1, 3,
	0, 2, 0, 2, 1, 1, 1, 1, 3, 1,
	3, 3, 3, 3, 3, 5, 3, 5, 3, 4,
	1, 1, 0, 1, 3,
}

var yyChk = [...]int16{
	-1000, -17, -1, -2, 4, 8, 29, -3, -6, -15,
	5, 6, 7, -6, -15, -15, 30, 31, 31, 31,
	-15, 30, 30, -4, -7, -8, 10, -13, -14, 33,
	24, 25, 14, 13, 18, 30, -5, 8, -8, 32,
	22, 21, 28, -13, 26, 26, 23, 33, 32, -9,
	9, 11, 29, -13, -13, -13, 34, 27, 33, 27,
	33, -14, -16, -14, 9, 18, -10, -11, 15, 15,
	34, 35, 12, 30, -12, 19, 20, 16, 17, 34,
	34, -14,
}

var yyDef = [...]int8{
	2, -2, 1, 3, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 7, 9, 0, 0,
	0, 6, 5, 8, 13, 14, 0, 28, 29, 0,
	0, 0, 40, 0, 41, 4, 10, 0, 15, 0,
	0, 0, 0, 0, 0, 0, 0, 42, 0, 20,
	17, 18, 22, 30, 31, 32, 33, 34, 0, 36,
	0, 38, 0, 43, 11, 12, 16, 0, 0, 0,
	39, 0, 21, 19, 23, 24, 25, 26, 27, 35,
	37, 44,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	33, 34, 3, 3, 35, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 31, 3,
	3, 32, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 29, 3, 30,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:58
		{
			yylex.(*yaraLexer).ruleSet = &ast.RuleSet{Rules: yyDollar[1].rules}
		}
	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yara.y:65
		{
			yyVAL.rules = nil
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yara.y:69
		{
			yyVAL.rules = append(yyDollar[1].rules, yyDollar[2].rule)
		}
	case 4:
		yyDollar = yyS[yypt-7 : yypt+1]
//line yara.y:76
		{
			yyVAL.rule = &ast.Rule{
				Name:      yyDollar[2].str,
				Meta:      yyDollar[4].meta,
				Strings:   yyDollar[5].stringDefs,
				Condition: yyDollar[6].expr,
			}
		}
	case 5:
		yyDollar = yyS[yypt-6 : yypt+1]
//line yara.y:85
		{
			yyVAL.rule = &ast.Rule{
				Name:      yyDollar[2].str,
				Strings:   yyDollar[4].stringDefs,
				Condition: yyDollar[5].expr,
			}
		}
	case 6:
		yyDollar = yyS[yypt-6 : yypt+1]
//line yara.y:93
		{
			yyVAL.rule = &ast.Rule{
				Name:      yyDollar[2].str,
				Meta:      yyDollar[4].meta,
				Condition: yyDollar[5].expr,
			}
		}
	case 7:
		yyDollar = yyS[yypt-5 : yypt+1]
//line yara.y:101
		{
			yyVAL.rule = &ast.Rule{
				Name:      yyDollar[2].str,
				Condition: yyDollar[4].expr,
			}
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:111
		{
			yyVAL.meta = yyDollar[3].meta
		}
	case 9:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yara.y:118
		{
			yyVAL.meta = nil
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yara.y:122
		{
			yyVAL.meta = append(yyDollar[1].meta, yyDollar[2].metaEntry)
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:129
		{
			yyVAL.metaEntry = &ast.MetaEntry{Key: yyDollar[1].str, Value: unquoteString(yyDollar[3].str)}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:133
		{
			yyVAL.metaEntry = &ast.MetaEntry{Key: yyDollar[1].str, Value: yyDollar[3].num}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:140
		{
			yyVAL.stringDefs = yyDollar[3].stringDefs
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:147
		{
			yyVAL.stringDefs = []*ast.StringDef{yyDollar[1].stringDef}
		}
	case 15:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yara.y:151
		{
			yyVAL.stringDefs = append(yyDollar[1].stringDefs, yyDollar[2].stringDef)
		}
	case 16:
		yyDollar = yyS[yypt-4 : yypt+1]
//line yara.y:158
		{
			yyVAL.stringDef = &ast.StringDef{
				Name:      yyDollar[1].str,
				Value:     yyDollar[3].strVal,
				Modifiers: yyDollar[4].mods,
			}
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:169
		{
			yyVAL.strVal = ast.TextString{Value: unquoteString(yyDollar[1].str)}
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:173
		{
			pattern, mods := parseRegex(yyDollar[1].str)
			yyVAL.strVal = ast.RegexString{Pattern: pattern, Modifiers: mods}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:178
		{
			yyVAL.strVal = ast.HexString{Tokens: yyDollar[2].hexTokens}
		}
	case 20:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yara.y:185
		{
			yyVAL.mods = ast.StringModifiers{}
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yara.y:189
		{
			yyVAL.mods = yyDollar[1].mods
			switch yyDollar[2].str {
			case "ascii":
				yyVAL.mods.Ascii = true
			case "base64":
				yyVAL.mods.Base64 = true
			case "fullword":
				yyVAL.mods.Fullword = true
			default:
				yylex.Error("unsupported modifier: " + yyDollar[2].str)
			}
		}
	case 22:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yara.y:206
		{
			yyVAL.hexTokens = nil
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yara.y:210
		{
			yyVAL.hexTokens = append(yyDollar[1].hexTokens, yyDollar[2].hexToken)
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:217
		{
			yyVAL.hexToken = ast.HexByte{Value: yyDollar[1].byt}
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:221
		{
			yyVAL.hexToken = ast.HexWildcard{}
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:225
		{
			jump, err := parseHexJump(yyDollar[1].str)
			if err != nil {
				yylex.Error(err.Error())
			}
			yyVAL.hexToken = jump
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:233
		{
			alt, err := parseHexAlt(yyDollar[1].str)
			if err != nil {
				yylex.Error(err.Error())
			}
			yyVAL.hexToken = alt
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:244
		{
			yyVAL.expr = yyDollar[3].expr
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:251
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:255
		{
			yyVAL.expr = ast.BinaryExpr{Op: "or", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:259
		{
			yyVAL.expr = ast.BinaryExpr{Op: "and", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:263
		{
			yyVAL.expr = ast.BinaryExpr{Op: "==", Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:270
		{
			yyVAL.expr = ast.ParenExpr{Inner: yyDollar[2].expr}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:274
		{
			yyVAL.expr = ast.AnyOf{Pattern: "them"}
		}
	case 35:
		yyDollar = yyS[yypt-5 : yypt+1]
//line yara.y:278
		{
			yyVAL.expr = ast.AnyOf{Pattern: yyDollar[4].str}
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:282
		{
			yyVAL.expr = ast.AllOf{Pattern: "them"}
		}
	case 37:
		yyDollar = yyS[yypt-5 : yypt+1]
//line yara.y:286
		{
			yyVAL.expr = ast.AllOf{Pattern: yyDollar[4].str}
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:290
		{
			yyVAL.expr = ast.AtExpr{Ref: ast.StringRef{Name: yyDollar[1].str}, Pos: yyDollar[3].expr}
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
//line yara.y:294
		{
			yyVAL.expr = ast.FuncCall{Name: yyDollar[1].str, Args: yyDollar[3].exprs}
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:298
		{
			yyVAL.expr = ast.StringRef{Name: yyDollar[1].str}
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:302
		{
			yyVAL.expr = ast.IntLit{Value: yyDollar[1].num}
		}
	case 42:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yara.y:309
		{
			yyVAL.exprs = nil
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yara.y:313
		{
			yyVAL.exprs = []ast.Expr{yyDollar[1].expr}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yara.y:317
		{
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].expr)
		}
	}
	goto yystack /* stack new state and value */
}
